
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 10 02:13:16 COT 2021
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_decremento = 54;
  public static final int Llave_c = 60;
  public static final int Op_rel_mayor = 40;
  public static final int Llave_a = 59;
  public static final int Back = 4;
  public static final int Linea = 2;
  public static final int Break = 19;
  public static final int Coma = 67;
  public static final int SYSTEM = 29;
  public static final int Parent_c = 58;
  public static final int Parent_a = 57;
  public static final int Corchete_c = 62;
  public static final int Corchete_a = 61;
  public static final int T_long = 9;
  public static final int Punto = 65;
  public static final int Default = 20;
  public static final int Op_bool_true = 55;
  public static final int T_char = 8;
  public static final int For = 34;
  public static final int Void = 16;
  public static final int Op_rel_diferente = 43;
  public static final int Else = 15;
  public static final int Resta = 37;
  public static final int Cin = 26;
  public static final int Suma = 36;
  public static final int Using = 23;
  public static final int ERROR = 71;
  public static final int Cadena = 12;
  public static final int Main = 63;
  public static final int Op_rel_igual = 42;
  public static final int Do = 32;
  public static final int STD = 25;
  public static final int Op_rel_izq = 46;
  public static final int P_coma = 64;
  public static final int Op_atr_mult = 50;
  public static final int Op_rel_menor = 41;
  public static final int Comilla_s = 5;
  public static final int Scanf = 31;
  public static final int Case = 18;
  public static final int IOStream = 22;
  public static final int T_float = 10;
  public static final int Op_atr_resto = 52;
  public static final int Op_atr_div = 51;
  public static final int RETURN = 28;
  public static final int T_byte = 6;
  public static final int If = 14;
  public static final int EOF = 0;
  public static final int T_bool = 13;
  public static final int Cout = 27;
  public static final int Numero = 70;
  public static final int Op_atr_adicion = 48;
  public static final int Division = 39;
  public static final int Op_rel_mayor_igual = 44;
  public static final int Dos_puntos = 66;
  public static final int error = 1;
  public static final int Op_atr_sustraccion = 49;
  public static final int Op_rel_menor_igual = 45;
  public static final int NameSpace = 24;
  public static final int Comillas = 3;
  public static final int Identificador = 69;
  public static final int Op_bool_false = 56;
  public static final int Op_incremento = 53;
  public static final int Include = 21;
  public static final int Modulo = 68;
  public static final int T_int = 7;
  public static final int Printf = 30;
  public static final int T_double = 11;
  public static final int Igual = 35;
  public static final int While = 33;
  public static final int Op_rel_der = 47;
  public static final int Multiplicacion = 38;
  public static final int Switch = 17;
}

