
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 07 16:57:13 COT 2021
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_decremento = 53;
  public static final int Comilla_s = 4;
  public static final int Coma = 66;
  public static final int Llave_c = 59;
  public static final int Llave_a = 58;
  public static final int Op_rel_menor_igual = 44;
  public static final int If = 13;
  public static final int T_char = 7;
  public static final int Void = 15;
  public static final int Op_atr_sustraccion = 48;
  public static final int Op_rel_igual = 41;
  public static final int Default = 19;
  public static final int Else = 14;
  public static final int Cout = 26;
  public static final int Op_rel_izq = 45;
  public static final int Break = 18;
  public static final int STD = 24;
  public static final int Corchete_c = 61;
  public static final int Corchete_a = 60;
  public static final int IOStream = 21;
  public static final int Punto = 64;
  public static final int Parent_c = 57;
  public static final int T_bool = 12;
  public static final int Op_atr_div = 50;
  public static final int Parent_a = 56;
  public static final int T_double = 10;
  public static final int While = 32;
  public static final int Division = 38;
  public static final int Op_rel_menor = 40;
  public static final int Cadena = 11;
  public static final int For = 33;
  public static final int P_coma = 63;
  public static final int EOF = 0;
  public static final int SYSTEM = 28;
  public static final int RETURN = 27;
  public static final int Op_rel_mayor = 39;
  public static final int Printf = 29;
  public static final int error = 1;
  public static final int Switch = 16;
  public static final int Linea = 2;
  public static final int ERROR = 69;
  public static final int Do = 31;
  public static final int Op_bool_false = 55;
  public static final int T_byte = 5;
  public static final int Op_atr_mult = 49;
  public static final int Op_rel_der = 46;
  public static final int Case = 17;
  public static final int Dos_puntos = 65;
  public static final int Scanf = 30;
  public static final int Op_rel_diferente = 42;
  public static final int T_int = 6;
  public static final int Identificador = 67;
  public static final int Using = 22;
  public static final int Cin = 25;
  public static final int Resta = 36;
  public static final int Op_bool_true = 54;
  public static final int Op_atr_resto = 51;
  public static final int T_long = 8;
  public static final int NameSpace = 23;
  public static final int Multiplicacion = 37;
  public static final int Op_incremento = 52;
  public static final int Numero = 68;
  public static final int Suma = 35;
  public static final int T_float = 9;
  public static final int Include = 20;
  public static final int Main = 62;
  public static final int Igual = 34;
  public static final int Op_atr_adicion = 47;
  public static final int Op_rel_mayor_igual = 43;
  public static final int Comillas = 3;
}

